name: Run unittests

on: [push, pull_request]

jobs:
  test:
    name: "Run unittests"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v5
      - run: pipx install poetry
      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"
          cache: "poetry"
      - run: poetry install --with dev --no-interaction
      - run: poetry run coverage run -m unittest
      - run: poetry run coverage report
      - run: poetry run coverage xml
      - uses: codecov/codecov-action@v5
